server {
    listen 8080;
    server_name elsam.dimasaris.xyz;

    root /var/www/apps/elsam/public;
    index index.php;

    client_max_body_size 20m;

    location = /healthz {
        access_log off;
        default_type text/plain;
        return 200 "ok";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass elsam:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        fastcgi_read_timeout 60;
    }

    location ~ /\.(?!well-known) { deny all; }
    location ~* \.(env|log|sql)$ { deny all; }
}
